BookLogApp/Pages/AddBook.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using BookLogAppBLL;  
using BookLogAppFactories; 
using BookLogAppInterfaces;

namespace BookLogApp.Pages
{
    public class AddBookModel : PageModel
    {
        private readonly IBookBLL _bookBLL;

        public AddBookModel()
        {
            _bookBLL = BookFactory.CreateBookBLL();
        }

        [BindProperty]
        public string Title { get; set; }

        [BindProperty]
        public string Author { get; set; }

        [BindProperty]
        public string Summary { get; set; }

        [BindProperty]
        public string ISBN { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            

            try
            {
                //BLL method to create the book
                _bookBLL.CreateBook(Title, Author, Summary, ISBN);

                return RedirectToPage("/Index");
            }
            catch (ArgumentException ex)
            {

                // Add the error to the ModelState to display in the view
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }
        }
    }
}

BookLogApp/Pages/AssignGenreToBook.cshtml.cs
using Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Factories;
using DomainModels;

namespace BookLogApp.Pages
{
    public class AssignGenreToBookModel : PageModel
    {
        private readonly IBookBLL _bookBLL;
        private readonly IGenreBLL _genreBLL;

        public List<Book> Books { get; set; }
        public List<Genre> Genres { get; set;}
        [BindProperty]
        public int SelectedBookId { get; set; }
        [BindProperty]
        public List<int> SelectedGenreIds { get; set; }
        public AssignGenreToBookModel()
        {
            _bookBLL = Factory.CreateBookBLL();
            _genreBLL = Factory.CreateGenreBLL();
        }

        public void OnGet()
        {
            Books = _bookBLL.GetBooks();
            Genres = _genreBLL.GetGenres();
        }

        public IActionResult OnPost()
        {
            try
            {
                if (SelectedBookId > 0 && SelectedGenreIds.Count > 0)
                {
                    foreach (int genreId in SelectedGenreIds)
                    {
                        _genreBLL.CreateBooksGenreRelation(SelectedBookId, genreId);
                    }
                    return RedirectToPage("/PagesForBooks/ViewBooks");
                }

            }
            catch (Exception)
            {
                Books = _bookBLL.GetBooks();
                Genres = _genreBLL.GetGenres();

                ModelState.AddModelError(string.Empty, "An error occured assigning genres to your book");
                return Page();
            }

            Books = _bookBLL.GetBooks();
            Genres = _genreBLL.GetGenres();

            return Page();
        }
    }
}

BookLogApp/Pages/CreateEntry.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DomainModels;
using Interfaces;
using Factories;

namespace BookLogApp.Pages
{
    public class CreateEntryModel : PageModel
    {
        private readonly IBookBLL _bookBLL;
        private readonly IJournalBLL _journalBLL;
        public Book Book { get; set; }
        public Journal Journal { get; set; }
        public string AnalyzedMood { get; set; }
        [BindProperty]
        public string Entry { get; set; }
        public CreateEntryModel()
        {
            _bookBLL = Factory.CreateBookBLL();
            _journalBLL = Factory.CreateJournalBLL();
        }
        public void OnGet(int id)
        {
            Book = _bookBLL.GetBookById(id);
            if (Book != null)
            {
                //TODO: simplify code, and error handling
                int journalId = _journalBLL.GetJournalEntryIdForBook(id);

                Journal journalEntry = _journalBLL.GetEntryAndBookById(journalId, id);
                if (journalEntry != null)
                {
                    Entry = journalEntry.Entry;
                }
            }
        }

        public IActionResult OnPost(int id)
        {
            try
            {
                 Book = _bookBLL.GetBookById(id);
                _journalBLL.UpsertJournalEntry(Entry, Book.ID);
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }
            
            return Page();
        }

        public IActionResult OnPostAnalyze(int id)
        {
            try
            {
                Book = _bookBLL.GetBookById(id);
                if (!string.IsNullOrEmpty(Entry))
                {
                    AnalyzedMood = _journalBLL.AnalyzeMood(Entry);
                }
                _journalBLL.UpsertJournalEntry(Entry, Book.ID);
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }
            
            return Page();
        }
    }
}

BookLogApp/Pages/DeleteBook.cshtml.cs
using BookLogAppFactories;
using BookLogAppInterfaces;
using DomainModelsLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookLogApp.Pages
{
    public class DeleteBookModel : PageModel
    {
        //prevent navigation through url to this page
        private readonly IBookBLL _bookBLL;

        public DeleteBookModel()
        {
            _bookBLL=BookFactory.CreateBookBLL();
        }
        public Book Book { get; set; }
        public IActionResult OnGet(int id)
        {
            _bookBLL.DeleteBook(id);
            return RedirectToPage("./ViewBooks");
        }
    }
}

BookLogApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace BookLogApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BookLogApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookLogApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

BookLogApp/Pages/PagesForBooks/AddBook.cshtml.cs
using Factories;
using Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace BookLogApp.Pages.PagesForBooks
{
    public class AddBookModel : PageModel
    {
        private readonly IBookBLL _bookBLL;

        public AddBookModel()
        {
            _bookBLL = Factory.CreateBookBLL();
            
        }

        [BindProperty]
        public string Title { get; set; }

        [BindProperty]
        public string Author { get; set; }

        [BindProperty]
        public string? Summary { get; set; }

        [BindProperty]
        public string ISBN { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                _bookBLL.CreateBook(Title, Author, Summary, ISBN);

                return RedirectToPage("/Index");
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }
        }
    }
}

BookLogApp/Pages/PagesForBooks/UpdateBook.cshtml.cs
using BLL;
using Factories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DomainModels;
using BookLogApp.ViewModels;
using System.Linq;
using Interfaces;

namespace BookLogApp.Pages.PagesForBooks
{
    public class UpdateBookModel : PageModel
    {
        private readonly IBookBLL _bookBLL;
        private readonly IGenreBLL _genreBLL;

        public UpdateBookModel()
        {
            _bookBLL = Factory.CreateBookBLL();
            _genreBLL = Factory.CreateGenreBLL();
        }

        [BindProperty]
        public BookViewModel BookViewModel { get; set; }

        public void OnGet(int id)
        {
            Book book = _bookBLL.GetBookById(id);
            BookViewModel = new BookViewModel
            {
                ID = book.ID,
                Title = book.Title,
                Summary = book.Summary,
                Author = book.Author,
                ISBN = book.ISBN,
                AvailableGenres = _genreBLL.GetGenres(),
                SelectedGenreIds = _bookBLL.LoadGenresForBook(id).Select(g => g.ID).ToList()
            };
        }

        public IActionResult OnPost()
        {
            if (BookViewModel == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                BookViewModel.AvailableGenres = _genreBLL.GetGenres();
                BookViewModel.SelectedGenreIds = _bookBLL.LoadGenresForBook(BookViewModel.ID).Select(g => g.ID).ToList();
                return Page();
            }

            Book bookToUpdate = new Book
            {
                ID = BookViewModel.ID,
                Title = BookViewModel.Title,
                Author = BookViewModel.Author,
                Summary = BookViewModel.Summary,
                ISBN = BookViewModel.ISBN
            };

            try
            {
                _bookBLL.UpdateBook(bookToUpdate);

                _genreBLL.DeleteBooksGenreRelationByBookId(bookToUpdate.ID);
                foreach (int genreId in BookViewModel.SelectedGenreIds)
                {
                    _genreBLL.CreateBooksGenreRelation(bookToUpdate.ID, genreId);
                }
            }
            catch (ArgumentException ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }

            
            return RedirectToPage("./ViewBooks");
        }
    }
}

BookLogApp/Pages/PagesForBooks/ViewBooks.cshtml.cs
using Factories;
using DomainModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Interfaces;

namespace BookLogApp.Pages.PagesForBooks
{
    public class ViewBooksModel : PageModel
    {
        private readonly IBookBLL _bookBLL;

        public ViewBooksModel()
        {
            _bookBLL = Factory.CreateBookBLL();
        }
        public List<Book> Books { get; set; }
        public void OnGet()
        {
            Books = _bookBLL.GetBooks();
            foreach(Book book in Books)
            {
                book.Genres = _bookBLL.LoadGenresForBook(book.ID);
            }
        }
    }
}

BookLogApp/Pages/UpdateBook.cshtml.cs
using BookLogAppFactories;
using BookLogAppInterfaces;
using DomainModelsLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookLogApp.Pages
{
    public class UpdateBookModel : PageModel
    {
        private readonly IBookBLL _bookBLL;

        public UpdateBookModel()
        {
            _bookBLL = BookFactory.CreateBookBLL();
        }

        [BindProperty] 
        public Book Book {get; set; } //TODO: create viewmodel for ui?
        public void OnGet(int id)
        {
            Book = _bookBLL.GetBookById(id);
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _bookBLL.UpdateBook(Book);
            return RedirectToPage("./ViewBooks");
        }
    }
}

BookLogApp/Pages/ViewBooks.cshtml.cs
using BookLogAppFactories;
using BookLogAppInterfaces;
using DomainModelsLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookLogApp.Pages
{
    public class ViewBooksModel : PageModel
    {
        private readonly IBookBLL _bookBLL;

        public ViewBooksModel()
        {
            _bookBLL=BookFactory.CreateBookBLL();
        }

        public List<Book> Books { get; set; }   
        public void OnGet()
        {
            Books=_bookBLL.GetBooks();
        }
    }
}

BookLogApp/Pages/AddBook.cshtml
@page
@model BookLogApp.Pages.AddBookModel
@{
    <h2>Add Book</h2>

    <form method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div>
            <label for="Title">Title:</label>
            <input id="Title" name="Title" asp-for="Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div>
            <label for="Author">Author:</label>
            <input id="Author" name="Author" asp-for="Author" />
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>

        <div>
            <label for="Summary">Summary:</label>
            <textarea id="Summary" name="Summary" asp-for="Summary"></textarea>
            <span asp-validation-for="Summary" class="text-danger"></span>
        </div>

        <div>
            <label for="ISBN">ISBN:</label>
            <input id="ISBN" name="ISBN" asp-for="ISBN" />
            <span asp-validation-for="ISBN" class="text-danger"></span>
        </div>


        <button type="submit">Add Book</button>
    </form>
}

BookLogApp/Pages/AssignGenreToBook.cshtml
@page
@model BookLogApp.Pages.AssignGenreToBookModel

<div class="container mt-4">
    <h2 class="mb-3">Assign genre to book</h2>
    @if (!ModelState.IsValid)
    {
        <div class="alert alert-danger">
            @foreach (Microsoft.AspNetCore.Mvc.ModelBinding.ModelError error in ModelState.Values.SelectMany(v => v.Errors))
            {
                <p>@error.ErrorMessage</p>
            }
        </div>
    }
    <form method="post" class="needs-validation" novalidate>
        <div class="mb-3">
            <label class="form-label">Select book:</label>
            <select asp-for="SelectedBookId" asp-items="@(new SelectList(Model.Books,"ID","Title"))" class="form-select">
                <option value="">Select a book</option>
            </select>
        </div>

        <div class="mb-3">
            <label class="form-label">Select Genre:</label>
            <div>
                @foreach (DomainModels.Genre genre in Model.Genres)
                {
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="SelectedGenreIds" value="@genre.ID" />
                        <label class="form-check-label">@genre.Name</label>
                    </div>
                }
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Assign Genre</button>
    </form>
</div>

BookLogApp/Pages/CreateEntry.cshtml
@page "{id:int}"
@model BookLogApp.Pages.CreateEntryModel

<div class="container mt-5">
    <h2 class="mb-4">Journal Entry for @Model.Book.Title</h2>

    <form method="post">
        <input type="hidden" asp-for="Book.ID" />
        <div class="form-group">
            <label asp-for="Entry">Write an entry</label>
            <textarea asp-for="Entry" class="form-control" rows="10"></textarea>
            <span asp-validation-for="Entry" class="text-danger"></span>
        </div>
        <br/>

        <button type="submit" class="btn btn-success">Submit Entry</button>

        <button type="submit" asp-page-handler="Analyze" class="btn btn-info">Analyze Mood</button>
    </form>

    <br/>
    @if (!string.IsNullOrEmpty(Model.AnalyzedMood))
    {
        <div class="alert alert-info">@Model.AnalyzedMood</div>
    }
</div>

BookLogApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="container mt-5">

    <div class="text-center">
        <h1 class="display-4">Welcome to the BookLogApp</h1>
        <p class="lead">Your personal log to track your book reading progress</p>
    </div>

    <div class="row mt-4">
        <div class="col-md-4">
            <h3>Manage Your Books</h3>
            <p>Keep track of all your books, authors, and summaries in one place.</p>
        </div>
        <div class="col-md-4">
            <h3>Organize by Genre</h3>
            <p>Categorize books into genres for easy retrieval and organization.</p>
        </div>
        <div class="col-md-4">
            <h3>Easy Access</h3>
            <p>Access your book collection from anywhere.</p>
        </div>
    </div>

    <div class="text-center mt-5">
        <a href="/PagesForBooks/ViewBooks" class="btn btn-primary">View Books</a>
        <a href="/PagesForGenres/ViewGenres" class="btn btn-secondary">View Genres</a>
    </div>


</div>

BookLogApp/Pages/UpdateBook.cshtml
@page "{id:int}"
@model BookLogApp.Pages.UpdateBookModel

<h2>Update @Model.Book.Title</h2>

<form method="post">
    <input type="hidden" asp-for="Book.ID" />

    <div>
        <label for="Title">Title:</label>
        <!-- Ensure the asp-for tag helper is correctly used for model binding -->
        <input id="Title" asp-for="Book.Title" />
    </div>

    <div>
        <label for="Author">Author:</label>
        <input id="Author" asp-for="Book.Author" />
    </div>

    <div>
        <label for="Summary">Summary:</label>
        <textarea id="Summary" asp-for="Book.Summary"></textarea>
    </div>

    <button type="submit">Update @Model.Book.Title</button>
</form>

BookLogApp/Pages/ViewBooks.cshtml
@page
@model BookLogApp.Pages.ViewBooksModel
<h2>Book List</h2>

<ul>
    @foreach (DomainModelsLayer.Book book in Model.Books)
    {
        <li>
            <a href="./UpdateBook/@book.ID"><strong>Title:</strong> @book.Title <br /></a>
            <strong>Author:</strong> @book.Author <br />
            <strong>Summary:</strong> @book.Summary <br />
            <strong>ISBN:</strong> @book.ISBN <br/>
            <a href="./DeleteBook/@book.ID">Delete @book.Title</a>

        </li>
    }
</ul>